---
# Create a secret in the openshift-config namespace containing the
# LDAP bind password and a configuration map containing the public CA
# certificate, if defined.

- block:
    - name: Check for existing LDAP bind secret
      command: "{{ oc }} get secret -n openshift-config ldap-bind-secret"
      register: ldap_bind_secret
      failed_when: ldap_bind_secret.rc > 1

    - name: Create LDAP bind secret
      command: >
        {{ oc }} create secret generic
          -n openshift-config ldap-bind-secret
          --from-literal=bindPassword={{ ldap_bind_password }}
      when: ldap_bind_secret.rc == 1
  when: ldap_bind_password is defined

- block:
    - name: Check for existing LDAP CA config map
      command: "{{ oc }} get configmap -n openshift-config ldap-ca-config-map"
      register: ldap_ca_config_map
      failed_when: ldap_ca_config_map.rc > 1

    - name: Create LDAP CA config map
      command: >
        {{ oc }} create configmap
          -n openshift-config ldap-ca-config-map
          --from-file=ca.crt={{ ldap_ca_cert }}
      when: ldap_ca_config_map.rc == 1
  when: ldap_ca_cert is defined
...
