---
# Create a secret in the openshift-config namespace containing a
# htpasswd file for local authentication. If the htpasswd secret
# already exists, we leave it unchanged.

- name: Check for existing htpasswd secret
  command: "{{ oc }} get secret -n openshift-config htpasswd-secret"
  register: htpasswd_secret
  failed_when: htpasswd_secret.rc > 1

- block:
    - name: Create temporary file
      tempfile:
        state: file
      register: htpasswd_file

    - name: Create htpasswd file
      htpasswd:
        path: "{{ htpasswd_file.path }}"
        mode: 0600
        name: admin
        password: "{{ local_admin_password }}"
      no_log: true

    - name: Create htpasswd secret
      command: >
        {{ oc }} create secret generic
          -n openshift-config htpasswd-secret
          --from-file=htpasswd={{ htpasswd_file.path }}

    - name: Delete temporary file
      file:
        path: "{{ htpasswd_file.path }}"
        state: absent
  when: htpasswd_secret.rc == 1
...
