---
- name: Apply OpenShift configuration manifests
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    template_path: ../templates/
  vars_files:
  - ../vars.yaml

  tasks:
  - import_tasks: apply-manifests.yaml
...
