---
- name: Generate OpenShift configuration manifests
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    template_path : ../templates/
    manifests_path: ../generated-manifests
  vars_files:
    - ../vars.yaml

  tasks:

  - fail:
      msg: "applied_config variable is not defined - nothing to do - exiting..."
    when: applied_config is not defined

  - name: Delete manifests dir
    file:
      path: "{{ manifests_path }}"
      state: absent

  - name: Create manifests dir
    file:
      path: "{{ manifests_path }}"
      state: directory

  - name: Populate filtered templates directory structure in manifests dir
    file:
      state: directory
      dest: "{{ manifests_path }}/{{ item }}"
    with_items: "{{ applied_config }}"
    
  - name: Populate filtered templates
    template:
      src: "{{ item.src }}"
      dest: "{{ manifests_path }}/{{ item.path | replace('yaml.j2','yaml')}}"
    with_filetree: "{{ template_path }}"
    when: item.path | dirname in applied_config and item.state == 'file'
...
